### PR TITLE
Using the right effects for last standers

### PR DESCRIPTION
**Pull request by DuyGamerLHB**
They were all using a pistol and the emissions of the rifle single fire sound and case for it had been left unreplaced for years
Not really a bug or a glitch, it's kinda like an imperfection

Oh and btw, I'm back, Carr. I've been pretty busy with school and stuff

### CODE REVIEW

**Review by BLOODWOLF333 — COMMENTED** [review]
This is good, go ahead and delete the incorrect/old lines so we dont have a bunch of messy notated-out code

**Comment by DuyGamerLHB** [comment]
Sure thing

**Review by BLOODWOLF333 — APPROVED** [review]

**Comment by BLOODWOLF333** [comment]
This errors, did you play test this before submitting?

**Comment by DuyGamerLHB** [comment]
I did tho, that's weird

**Pull request merged**
