### PR TITLE
Moved weapon decorates to subfolder

### PR DESCRIPTION
**Pull request by Real-Gecko**
Hey guys! I've decided to organize the code a little bit, check this out.

### CODE REVIEW

**Comment by BLOODWOLF333** [comment]
I just now saw this PR

**Comment by Real-Gecko** [comment]
It's up to you to decide if you want this code refactoring, just wanted to help a little bit.

**Comment by BLOODWOLF333** [comment]
Honestly no offense I just dont want this.  Im used to where all these files are for the last two years and there's no need to change something that isn't broken and is going to make things slower cause now I would have to enter and exit a bunch of folders to navigate through the mod.

**Comment by Real-Gecko** [comment]
Yeah, man, as you wish.

**Pull request closed without merging**
