### PR TITLE
Fixes, batch 1:

### PR DESCRIPTION
**Pull request by Zodomaniac**
1) For Shotgun, Assault shotgun, Rocket launcher and Railgun crosshair now disappears when ironsighting as it should.
2) Proper fire rates of dual guns.
3) Plasma rifle now fires faster (skips a frame) in Tactical mode.

### CODE REVIEW

**Comment by BLOODWOLF333** [comment]
Sorry, I didnt have a pull request template setup yet.  Let's try to keep them as single-issue items just for simplicity sake.  And the master's pk3 i had already reverted my slow down changes to the dual weapon fire rates, have you tested them and found them still wrong?  Plasma rifle firing faster in tactical I'm good with.  I'm comparing how you did your iron sights to what I changed last night.

**Comment by Zodomaniac** [comment]
>And the master's pk3 i had already reverted my slow down changes to the dual weapon fire rates, have you tested them and found them still wrong?

I didn't know you reverted them.
Another thing I changed is that I enabled dual-wielding pistols in Tactical mode.

**Comment by BLOODWOLF333** [comment]
image
Are you working on this in slade?  Your files are out of order like Plasma.txt is under the Special Effects marker and all the modified weapons are down at the bottom instead of under the Weapons marker.  That order that files are read in the pk3 (top to bottom) can cause issues with inheritance I have experienced.

**Comment by Zodomaniac** [comment]
Edited the latest version (after MG grenade fix) re-ordering the files.
file order

**Comment by BLOODWOLF333** [comment]
Ok let's redo this.  I broke all the files out of the pk3 because it's too much of a PITA to try and compare all the changes in slade or with Notepad++.  And I dont want dual wield pistols for tactical mode.  I dont agree with it because dual pistols is Hollywood and is not tactical so that breaks the "theme" of that game mode and is why i removed them from it.  Sorry Im still figuring out how to organize a github project and what is the better way to do things.

**Pull request closed without merging**
